files:
  - source: /src/lib/nyx-gtk/po/nyx-gtk.pot
    translation: /src/lib/nyx-gtk/po/%osx_locale%.po
  - source: /src/bin/nyx-app/po/nyx-app.pot
    translation: /src/bin/nyx-app/po/%osx_locale%.po
