
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#pragma once

#include <glib-object.h>
#include <nyx/nyx-visibility.h>

G_BEGIN_DECLS

/* enumerations from "nyx-enums.h" */

NYX_API
GType nyx_player_state_get_type (void);
#define NYX_TYPE_PLAYER_STATE (nyx_player_state_get_type())

NYX_API
GType nyx_player_seek_method_get_type (void);
#define NYX_TYPE_PLAYER_SEEK_METHOD (nyx_player_seek_method_get_type())

NYX_API
GType nyx_player_message_destination_get_type (void);
#define NYX_TYPE_PLAYER_MESSAGE_DESTINATION (nyx_player_message_destination_get_type())

NYX_API
GType nyx_queue_progression_mode_get_type (void);
#define NYX_TYPE_QUEUE_PROGRESSION_MODE (nyx_queue_progression_mode_get_type())

NYX_API
GType nyx_marker_type_get_type (void);
#define NYX_TYPE_MARKER_TYPE (nyx_marker_type_get_type())

NYX_API
GType nyx_stream_type_get_type (void);
#define NYX_TYPE_STREAM_TYPE (nyx_stream_type_get_type())

NYX_API
GType nyx_discoverer_discovery_mode_get_type (void);
#define NYX_TYPE_DISCOVERER_DISCOVERY_MODE (nyx_discoverer_discovery_mode_get_type())

NYX_API
GType nyx_enhancer_param_flags_get_type (void);
#define NYX_TYPE_ENHANCER_PARAM_FLAGS (nyx_enhancer_param_flags_get_type())

NYX_API
GType nyx_reactable_item_updated_flags_get_type (void);
#define NYX_TYPE_REACTABLE_ITEM_UPDATED_FLAGS (nyx_reactable_item_updated_flags_get_type())

G_END_DECLS

/* Generated data ends here */

